package com.amn.courses.controllers;

import com.amn.courses.dto.UserRepository;
import com.amn.courses.models.User;
import net.minidev.json.JSONObject;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.Optional;

@Controller
@RequestMapping(path = "/user")
public class UserController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @PostMapping(path="", produces= MediaType.APPLICATION_JSON_VALUE) // Map ONLY POST Requests
    public @ResponseBody ResponseEntity<Object> addNewUser (@RequestBody User user) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        for (User u : userRepository.findAll()) {
            if(u.getUsername().equals(user.getUsername())){
                JSONObject entity = new JSONObject();
                entity.put("message","No double usernames");
                return new ResponseEntity<Object>(entity,HttpStatus.BAD_REQUEST);
            }
        }

        userRepository.save(user);
        JSONObject entity = new JSONObject();
        entity.put("message","Saved");
        return new ResponseEntity<Object>(entity,HttpStatus.OK);
    }

    @GetMapping(path="")
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }

    @GetMapping(path="{id}", produces= MediaType.APPLICATION_JSON_VALUE)
    public @ResponseBody ResponseEntity<Object> getUser(@PathVariable(value="id") Integer id) {
        // This returns a JSON or XML with the users
        Optional<User> user = userRepository.findById(id);
        if(user.isEmpty()) {
            JSONObject entity = new JSONObject();
            entity.put("message","Not Found");
            return new ResponseEntity<Object>(entity,HttpStatus.NOT_FOUND);
        }
        else {
            return ResponseEntity.ok(user);
        }
    }

    @DeleteMapping(path="/{id}", produces= MediaType.APPLICATION_JSON_VALUE)
    public @ResponseBody ResponseEntity<Object> deleteUser(@PathVariable(value="id") Integer id) {
        userRepository.deleteById(id);
        JSONObject entity = new JSONObject();
        entity.put("message","Deleted");
        return new ResponseEntity<Object>(entity,HttpStatus.OK);
    }

}
