package com.amn.courses.controllers;

import com.amn.courses.dto.UserRepository;
import com.amn.courses.models.User;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller
@RequestMapping(path = "/user")
public class UserController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @PostMapping(path="") // Map ONLY POST Requests
    public @ResponseBody String addNewUser (
            @RequestParam String name,
            @RequestParam String email,
            @RequestParam String username,
            @RequestParam String password
    ) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        User n = new User();
        n.setName(name);
        n.setEmail(email);
        n.setUsername(username);
        n.setPassword(password);

        for (User user : userRepository.findAll()) {
            if(user.getUsername().equals(n.getUsername())){
                ResponseEntity.status(HttpStatus.BAD_REQUEST);
                return "No double usernames";
            }
        }

        userRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="")
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }

    @DeleteMapping(path="")
    public @ResponseBody String deleteUser(
            @RequestParam Integer id
    ) {
        userRepository.deleteById(id);
        return "Deleted";
    }

}
